# network architecture
# encoder related
# encoder: unimodal_branchformer
encoder: e_branchformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    attention_layer_type: rel_selfattn
    pos_enc_layer_type: rel_pos
    rel_pos_type: latest
    cgmlp_linear_units: 1024
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 1024
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31
    interctc_layer_idx: [6,9,12]
    interctc_use_conditioning: true

# # decoder related
decoder: unimodal_transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    interctc_layer_idx: [2,4]
    interctc_use_conditioning: true

# hybrid CTC/attention
model_conf:
    ctc_weight: 1
    interctc_weight_enc: 0.3
    interctc_weight_dec: 0.2
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: numel
batch_bins: 40000000

# optimization related
accum_grad: 1
grad_clip: 5
max_epoch: 70
best_model_criterion:
-   - valid
    - cer
    - min
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.001
   weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 35000

num_workers: 4      # num of workers of data loader
use_amp: true      # automatic mixed precision
unused_parameters: false    # set as true if some params are unused in DDP

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
