# network architecture
# encoder related
encoder: mamba
encoder_conf:
    output_size: 512
    num_blocks: 36
    dropout_rate: 0.1
    input_layer: causal_conv2d
    rms_norm: true
    fused_add_norm: true
    residual_in_fp32: true
    normalize_before: true
    lookahead_kernel: 29

# decoder related
decoder: unimodal_transformer
decoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false


# minibatch related
batch_type: folded
batch_size: 128
num_iters_per_epoch: 7126

# optimization related
accum_grad: 2
grad_clip: 5.0
max_epoch: 150
log_interval: 200
val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - cer
    - min
keep_nbest_models: 10

optim: adamw
optim_conf:
   lr: 0.0005
   weight_decay: 0.1
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 30000


num_workers: 4      # num of workers of data loader
use_amp: true      # automatic mixed precision
unused_parameters: false    # set as true if some params are unused in DDP

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
